wording, checks

diff --git a/tracks/a4mw-eap-sso/02-a4mw-eap-sso-first-deployment/check-control b/tracks/a4mw-eap-sso/02-a4mw-eap-sso-first-deployment/check-control
--- a/tracks/a4mw-eap-sso/02-a4mw-eap-sso-first-deployment/check-control
+++ b/tracks/a4mw-eap-sso/02-a4mw-eap-sso-first-deployment/check-control
@@ -15,3 +15,8 @@ if ! $CMD --tags=check-inventory -vv; then
  echo "FAIL: ${INVENTORY} inventory not found. Remember it's case-sensitive! Please try again."
  exit 1
 fi
+
+if ! curl -k https://jbcs-eap/mcm | grep '/addressbook'; then
+ echo "FAIL: addressbook application is not deployed in JBoss EAP; Please try again"
+ exit 1
+fi
diff --git a/tracks/a4mw-eap-sso/04-a4mw-eap-sso-redeploy/check-control b/tracks/a4mw-eap-sso/04-a4mw-eap-sso-redeploy/check-control
--- a/tracks/a4mw-eap-sso/04-a4mw-eap-sso-redeploy/check-control
+++ b/tracks/a4mw-eap-sso/04-a4mw-eap-sso-redeploy/check-control
@@ -1,4 +1,13 @@
 #!/bin/bash
-set -e
 
+cd /home/rhel/eap-sso && git log -1 -p -- inventory/group_vars/eap.yml | tail -n 3 | grep -q "+app_url: https://github.com/guidograzioli/keycloak/raw/instruqt/addressbook-1.1.0.war"
+if [ $? -ne 0 ]; then
+  echo "FAIL: Your challenge failed because of the inventory/group_vars/eap.yml file in the git repository has not been correctly updated"
+  exit 1
+fi
 
+cd /home/rhel/eap-sso && git log -1 -p -- inventory/group_vars/eap.yml | tail -n 3 | grep -q -- '[-]app_url: https://github.com/guidograzioli/keycloak/raw/instruqt/addressbook-1.0.0.war'
+if [ $? -ne 0 ]; then
+  echo "FAIL: Your challenge failed because of the inventory/group_vars/eap.yml file in the git repository has not been correctly updated"
+  exit 1
+fi
diff --git a/tracks/a4mw-eap-sso/05-a4mw-eap-sso-collections/check-control b/tracks/a4mw-eap-sso/05-a4mw-eap-sso-collections/check-control
--- a/tracks/a4mw-eap-sso/05-a4mw-eap-sso-collections/check-control
+++ b/tracks/a4mw-eap-sso/05-a4mw-eap-sso-collections/check-control
@@ -8,4 +8,14 @@
 
 echo "This is the check script"
 
+if ! curl -k https://jbcs-eap/mcm | grep '/addressbook'; then
+ echo "FAIL: addressbook application is not deployed in JBoss EAP; Please try again"
+ exit 1
+fi
+
+if ! curl -k https://jbcs-eap/mcm | grep '/auth'; then
+ echo "FAIL: Single Sign-On is not attached to JBCS modcluster; Please try again"
+ exit 1
+fi
+
 exit 0
diff --git a/tracks/a4mw-eap-sso/06-a4mw-eap-sso-auth-realm/check-control b/tracks/a4mw-eap-sso/06-a4mw-eap-sso-auth-realm/check-control
--- a/tracks/a4mw-eap-sso/06-a4mw-eap-sso-auth-realm/check-control
+++ b/tracks/a4mw-eap-sso/06-a4mw-eap-sso-auth-realm/check-control
@@ -1,11 +1,32 @@
 #!/bin/sh
 #
-# This script runs when the platform check the challenge.
-#
-# The platform determines if the script was successful using the exit code of this
-# script. If the exit code is not 0, the script fails. 
-#
 
-echo "This is the check script"
+grep -q 'import_playbook: sso_realm.yml' /home/rhel/eap-sso/deploy.yml
+if [ $? -ne 0 ]; then
+  echo "FAIL: Your challenge failed because the file deploy.yml in the git repository has not been correctly updated"
+  exit 1
+fi
 
+grep -q 'secure-deployment:' /home/rhel/eap-sso/templates/eap_ymlconfig.yml.j2
+if [ $? -ne 0 ]; then
+  echo "FAIL: Your challenge failed because the file templates/eap_ymlconfig.yml.j2 in the git repository has not been correctly updated"
+  exit 1
+fi
+
+grep -q 'realm_clients:' /home/rhel/eap-sso/inventory/group_vars/sso.yml
+if [ $? -ne 0 ]; then
+  echo "FAIL: Your challenge failed because the file inventory/group_vars/sso.yml in the git repository has not been correctly updated"
+  exit 1
+fi
+
+if [ ! -f /home/rhel/eap-sso/sso_realm.yml ]; then
+  echo "FAIL: Your challenge failed because the file sso_realm.yml has not been created"
+  exit 1
+fi
+
+grep -q 'name: redhat.sso.sso_realm' /home/rhel/eap-sso/sso_realm.yml
+if [ $? -ne 0 ]; then
+  echo "FAIL: Your challenge failed because the file sso_realm.yml in the git repository has not been correctly updated"
+  exit 1
+fi
 exit 0
